import { Injectable } from '@angular/core';
import { Iwebsites } from '../interfaces/websites.model';

@Injectable({
  providedIn: 'root'
})
export class WebsitesService {
  websites:Iwebsites[] = [
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
  ]

  mainPageWebsites:Iwebsites[] = [
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
    {
      img:'assets/images/websites/Lopstudios.png',
      title:'Lopstudios',
      gitReq:'https://github.com/xr11ku/Loopstudios',
      liveLink:'https://xr11ku.github.io/Loopstudios/'
    },
  ]
}
